### ISSUE TITLE
Does not work. 

### ISSUE THREAD

**Issue by Astral-Crescent** [EardwulfC/EardwulfDoesMods_PublicMods#3]
No matter what I do, I cannot get this mod to work. No keybind works, and yes I did read your instructions. No combination of anything with "E" works. The config shows up in-game fine, but the mod does not work.

**Comment by EardwulfC** [comment]
I used this mod earlier today with no issues.  Will need steps to reproduce the issue.  I only support my mods on Comfy Valheim, so conflicting mods that are not used on Comfy will not be supported.

**Comment by EardwulfC** [comment]
No update provided with steps to reproduce - closing issue.
