### ISSUE TITLE
Mod no longer works with Bogwitch patch

### ISSUE THREAD

**Issue by Tolagarf** [EardwulfC/EardwulfDoesMods_PublicMods#4]
Patch 0.219.14 (Bogwitch) is incompatible with this mod.
<img width="1096" alt="2024-11-05" src="https://github.com/user-attachments/assets/167c41f2-c377-48b6-acb1-41ecad663109">

**Comment by EardwulfC** [comment]
Thank you for the report. I’m aware in this case and have a fix in the works. I’ll try to remember to post it tonight.

**Comment by EardwulfC** [comment]
Patch has been released *and* I've accounted for the new Farming skill to give a skill up per plant placed.
